baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'scuttlerpod'
theme = 'scuttle'

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'blog'
    pageRef = '/blog'
    weight = 15
  [[menus.main]]
    name = 'music'
    pageRef = '/music'
    weight = 20
  [[menus.main]]
    name = 'photos'
    pageRef = 'https//www.flickr.com/photos/203485108@N06/'
    weight = 21
  [[menus.main]]
    name = 'projects'
    pageRef = '/projects'
    weight = 30
  [[menus.main]]
    name = 'contact'
    pageRef = '/contact'
    weight = 40
  [[menus.main]]
    name = 'git'
    pageRef = 'https://git.sr.ht/~minilop/'
    weight = 50

[output]
  blog = ['html', 'rss']

[taxonomies]
  tags = "tags"
