baseURL = 'https://example.org/'
languageCode = 'en-GB'
title = 'scuttlerpod'
theme = 'scuttle'

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'music'
    pageRef = '/music'
    weight = 20
  [[menus.main]]
    name = 'projects'
    pageRef = '/projects'
    weight = 30
  [[menus.main]]
    name = 'contact'
    pageRef = '/contact'
    weight = 40

[taxonomies]
  music = "music"
  project = "projects"
  contact = "contacts"
